data=[
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "2gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "hd",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["2 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) HD Display","13MP + 2MP + 2MP | 13MP Front Camera","3000 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "3gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["3 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "APPLE",
        "star": "4.7 ★",
        "rating": "53,457",
        "review": "22,040",
        "price": "1,10,000",
        "img": "img/apple.jpeg",
        "ram": "8gb",
        "internalstorage": "128gb",
        "os": "ios",
        "processor": "ios",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["8 GB RAM | 256 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","12MP + 12MP | 12MP Front Camera","4500 mAh Battery", "A14 Bionic Chip with Next Generation Neural Engine Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "NOKIA",
        "star": "3.9 ★",
        "rating": "38,454",
        "review": "15,356",
        "img": "img/nokia.jpeg",
        "price": "18,000",
        "ram": "3gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "others",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["3 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 8MP Front Camera","4500 mAh Battery", "MediaTek Helio G85 Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "SAMSUNG",
        "star": "4.3 ★",
        "rating": "10,320",
        "review": "2,472",
        "img": "img/samsung.jpeg",
        "price": "35,999",
        "ram": "2gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "others",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["2 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","64MP + 8MP + 2MP | 32MP Front Camera","6500 mAh Battery", "MediaTek Helio G90 Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "6gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "n",
        "type": "smartphone",
        "specification": ["6 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "12gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["12 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 13MP Front Camera","2500 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "8gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["8 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "6gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["6 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD Display","13MP + 2MP + 2MP | 13MP Front Camera","5000 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "4gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "m",
        "type": "smartphone",
        "specification": ["4 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "REALME",
        "star": "4.2 ★",
        "rating": "32,105",
        "review": "5,459",
        "price": "14,999",
        "img": "img/realme.jpeg",
        "ram": "12gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["12 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 5MP + 2MP | 16MP Front Camera","2500 mAh Battery", "Snapdragon 720g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "1gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["1 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "3gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd",
        "osversion": "m",
        "type": "smartphone",
        "specification": ["3 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 13MP Front Camera","2300 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "2gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["2 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "REALME",
        "star": "4.2 ★",
        "rating": "32,105",
        "review": "5,459",
        "price": "14,999",
        "img": "img/realme.jpeg",
        "ram": "12gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["12 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 5MP + 2MP | 16MP Front Camera","4500 mAh Battery", "Snapdragon 720g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "8gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "o",
        "type": "smartphone",
        "specification": ["8 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "12gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["12 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 13MP Front Camera","5000 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "REALME",
        "star": "4.2 ★",
        "rating": "32,105",
        "review": "5,459",
        "price": "14,999",
        "img": "img/realme.jpeg",
        "ram": "12gb",
        "internalstorage": "128gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["12 GB RAM | 128 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 5MP + 2MP | 16MP Front Camera","4500 mAh Battery", "Snapdragon 720g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "4gb",
        "internalstorage": "8gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["4 GB RAM | 8 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 13MP Front Camera","5000 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "2gb",
        "internalstorage": "16gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["2 GB RAM | 16 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "POCO",
        "star": "4.6 ★",
        "rating": "30,000",
        "review": "5,000",
        "img": "img/pocom3.jpeg",
        "price": "15,000",
        "ram": "2gb",
        "internalstorage": "8gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "hd",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["2 GB RAM | 8 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) HD Display","13MP + 2MP + 2MP | 13MP Front Camera","3500 mAh Battery", "Snapdragon 732g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "MI",
        "star": "4.4 ★",
        "rating": "53,300",
        "review": "15,560",
        "price": "24,999",
        "img": "img/mi.jpeg",
        "ram": "3gb",
        "internalstorage": "16gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd",
        "osversion": "o",
        "type": "smartphone",
        "specification": ["3 GB RAM | 16 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD Display","108MP + 8MP + 2MP + 2MP | 16MP Front Camera","4820 mAh Battery", "Snapdragon 750g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "REALME",
        "star": "4.2 ★",
        "rating": "32,105",
        "review": "5,459",
        "price": "14,999",
        "img": "img/realme.jpeg",
        "ram": "6gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "snapdragon",
        "resolution": "fhd+",
        "osversion": "p",
        "type": "smartphone",
        "specification": ["6 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 5MP + 2MP | 16MP Front Camera","4500 mAh Battery", "Snapdragon 720g Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "APPLE",
        "star": "4.7 ★",
        "rating": "53,457",
        "review": "22,040",
        "price": "1,10,000",
        "img": "img/apple.jpeg",
        "ram": "8gb",
        "internalstorage": "256gb",
        "os": "ios",
        "processor": "ios",
        "resolution": "fhd+",
        "osversion": null,
        "type": "smartphone",
        "specification": ["8 GB RAM | 256 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","12MP + 12MP | 12MP Front Camera","6200 mAh Battery", "A14 Bionic Chip with Next Generation Neural Engine Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "NOKIA",
        "star": "3.9 ★",
        "rating": "38,454",
        "review": "15,356",
        "img": "img/nokia.jpeg",
        "price": "18,000",
        "ram": "3gb",
        "internalstorage": "32gb",
        "os": "android",
        "processor": "others",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["3 GB RAM | 32 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","13MP + 2MP + 2MP | 8MP Front Camera","4500 mAh Battery", "MediaTek Helio G85 Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    },
    {
        "name": "SAMSUNG",
        "star": "4.3 ★",
        "rating": "10,320",
        "review": "2,472",
        "img": "img/samsung.jpeg",
        "price": "35,999",
        "ram": "3gb",
        "internalstorage": "64gb",
        "os": "android",
        "processor": "others",
        "resolution": "fhd+",
        "osversion": "q",
        "type": "smartphone",
        "specification": ["3 GB RAM | 64 GB ROM | Expandable Upto 256 GB","16.51 cm (6.5 inch) FHD+ Display","64MP + 8MP + 2MP | 32MP Front Camera","6500 mAh Battery", "MediaTek Helio G90 Processor", "1 Year Warranty for Mobile and 6 Months for Accessories"]
    }
]
